services:
  postgres:
    image: postgres:16
    container_name: postgres16
    restart: unless-stopped
    environment:
      POSTGRES_DB: bancopost
      POSTGRES_USER: usuariosuser
      POSTGRES_PASSWORD: usuariospassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: